apiVersion: v1
kind: Secret
metadata:
  name: root-pass
  namespace: default
data:
  password: cGFzc3dvcmQ=
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: default
data:
  password: cGFzc3dvcmQ=
type: Opaque
